apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandy-argocd-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx
          ports:
          - containerPort: 80








